### ISSUE TITLE
Snooping on base

### ISSUE THREAD

**Issue by timholy** [ihnorton/HackThatBase.jl#1]
I'm in the early planning stages of an idea and wondering whether this package might be the right "home" for this code. It's motivated by https://github.com/JuliaLang/julia/pull/10911, where I'm replacing Julia's core `NTuple{N,T}` type with `Tuple{Vararg{T,N}}`. Unsurpringly, this has me attempting to modify vararg and type intersection code; that's all pretty low level, and it's descended into a game of chase-the-segfault.

It occurred to me today that what I need is to capture a whole bunch of test cases of the C code. The idea might be to insert a few lines into whatever function you want to "snoop" on (in its working version on master) and have it store a copy of its inputs and outputs in a JLD file. Then I can run my broken version on those test cases and see which ones fail.

Like I said, it's early days, and I don't yet have a clear idea how generic I can make this. But should I start playing around assuming this might be a home for such code, or should I plan on putting it elsewhere?

**Comment by ihnorton** [comment]
I briefly thought about proposing to put this in base, but it is perfectly usable, and more flexible, here.

So: yes, this can be a welcoming home for all manner of wayward and subversive code :japanese_goblin: The idea and the name were both whims to start, but the code works pretty well -- and the name fits.

I have a few ideas for improvements and extensions to the basic idea of the current macro. I will very likely also add more helper functions to set-up and call different parts of inference (because that is where I am stuck at the moment). I may also add some code for diff'ing expressions and AST rewriting.

**Comment by timholy** [comment]
I really like your macro. I'm having second thoughts about my idea; while it's not too hard to imagine getting to the point of capturing the input/output of a working build, the ability to feed the results as testcases for a broken julia seems much more dicey. Your julia would already have to be very functional in order to load JLD, for example.

I guess the alternative is to set up a whole C-side testing framework, but I don't have time to tackle that now.

**Comment by ihnorton** [comment]
Yeah, testing changes in a broken system is hard. Depending on how extensive your changes are, you could make the "broken path" conditional on some global flag, and only change that flag after you've done the initial setup.

> I guess the alternative is to set up a whole C-side testing framework, but I don't have time to tackle that now.

One thing I've often about is how feasible it would be to dlopen a second `libjulia` instance and call into it. So you could have both "good" and "bad" copies, do the setup in the first, and ccall in via the embedding API to run tests on the second. I think this might work if you set up your RTLD flags correctly so that globals are resolved privately (RTLD_DEEPBIND does this on linux, I think). This would avoid the need to write much setup code in C. Haven't tried it yet, though :)

(semi-related mailing list post: https://groups.google.com/forum/#!topic/julia-dev/F4B9OW9hMAo)
